spring:
  application:
    name: coupon-eureka

server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    #标识是否从Eureka Server 获取注册信息，默认是true.如果这个节点Eureka Server不需要同步其他节点的数据，设置为false
    fetch-registry: false
    #是否将自己注册到Eureka Server 由于当前是单节点的Eureka Server 需要设置为false
    register-with-eureka: false
    #用于设置Eureka server 所在的地址，查询服务和注册服务都要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/